### ISSUE TITLE
[TypeError: refs.includes is not a function]

### ISSUE THREAD

**Issue by josephearl** [elasticio/odata2openapi#2]
I'm trying to parse a metadata XML file and receiving the error `[TypeError: refs.includes is not a function]`.

I've attached the metadata document I'm trying to parse:
[$metadata.xml.txt](https://github.com/akorchev/odata2openapi/files/536882/metadata.xml.txt)

**Comment by josephearl** [comment]
This was caused because I had an old node version (`5.11`) activated for another project which did not support `Array.includes`. Switching to node `6.9.0` fixed this.

**Comment by akorchev** [comment]
I have to fix that by specifying the engine in package.json.
