### ISSUE TITLE
entitySets.forEach is not a function

### ISSUE THREAD

**Issue by mkarpuk** [elasticio/odata2openapi#21]
Trying this lib with a test metadata from http://services.odata.org/V4/Northwind/Northwind.svc/$metadata (simply copy output to the `const xml = '<paste content here>';`). The provided sample failed with 
```
TypeError: entitySets.forEach is not a function
    at pathsRecursive (node_modules\odata2openapi\dist\convert.js:522:16)
    at convert (node_modules\odata2openapi\dist\convert.js:877:17)
```
I've tested both locally and on the https://www.npmjs.com/package/odata2openapi?activeTab=readme with 'test in your browser' feature

**Comment by jerbob92** [comment]
I also have this error.

**Comment by jhorbulyk** [comment]
Documentation is updated in #15

**Comment by gregorwolf** [comment]
Hey @akorchev it would be great if you could merge @jhorbulyk 's pull request #15 which should fix this issue.

**Comment by jorgt** [comment]
Ran into the same thing, had a different fix documented in another issue. This is probably better... Please merge. https://github.com/akorchev/odata2openapi/issues/19

**Comment by akorchev** [comment]
Merged!
