### ISSUE TITLE
Support for Edm.Date for OData v4

### ISSUE THREAD

**Issue by sindhu-pvp** [elasticio/odata2openapi#38]
We are trying to convert OData v4 to open api using the library and found that the `Edm.Date` type is being converted to an `object`. We also want the support for `Edm.Date`.

**Comment by sindhu-pvp** [comment]
To be very precise; when we try to convert a field of type `Edm.Date` the parsed output is of type:
`<type>object</type>` whereas the expected output should be of the form ` <type>string</type> <format>date</format>`

**Comment by sindhu-pvp** [comment]
Can someone please give me access to push a branch that fixes the same?

**Comment by jhorbulyk** [comment]
> Can someone please give me access to push a branch that fixes the same?

No.  You need to either create your own fork and open a Pull Request from your fork or create a Pull Request from a patch file.  We will also require you to sign our contributor license agreement (CLA) before we can accept your change.
