### ISSUE TITLE
How to get this to work with https://graph.microsoft.com/beta/$metadata (V4 vs V1)

### ISSUE THREAD

**Issue by chauey** [elasticio/odata2openapi#6]
I got an error trying to convert the microsoft graph metatdata.

Error:
TypeError: Cannot read property 'map' of undefined
    at parseEntityType (http://localhost:3001/main.bundle.js:34425:43)
    at parseEntitySet (http://localhost:3001/main.bundle.js:34419:21)
    at http://localhost:3001/main.bundle.js:34411:20
    at Array.map (native)
    at parseEntitySets (http://localhost:3001/main.bundle.js:34407:41)...

I noticed https://graph.microsoft.com/beta/$metadata has version 4.0 vs 1.0 by the example.
<edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0">
<edmx:DataServices>
<Schema xmlns="http://docs.oasis-open.org/odata/ns/edm" Namespace="microsoft.graph">

http://services.odata.org/V3/Northwind/Northwind.svc/$metadata
<edmx:Edmx xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx" Version="1.0">
<edmx:DataServices xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata" m:DataServiceVersion="1.0" m:MaxDataServiceVersion="3.0">
<Schema xmlns="http://schemas.microsoft.com/ado/2008/09/edm" Namespace="NorthwindModel">

Thanks!

**Comment by chauey** [comment]
I put in a PR for this here: https://github.com/akorchev/odata2openapi/pull/7
Some "EntityType" nodes do not have "Properties" nodes and caused this problem

**Comment by akorchev** [comment]
We've made some changes recently that allow better handling of the MSGraph schema.
